# Generated by Django 3.0.8 on 2020-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='words',
            field=models.IntegerField(null=True),
        ),
    ]
