# Generated by Django 3.0.8 on 2020-08-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20200802_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
