# Generated by Django 3.0.8 on 2020-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_auto_20200802_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
