# Generated by Django 3.0.8 on 2020-08-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_auto_20200802_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='file',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='title',
        ),
    ]
