# Generated by Django 3.0.8 on 2020-08-02 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_auto_20200802_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 16, 31, 16, 344298, tzinfo=utc), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='words',
            field=models.IntegerField(),
        ),
    ]
