# Generated by Django 3.0.8 on 2020-08-05 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_auto_20200805_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='currency',
            field=models.CharField(default='SEK', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 7, 11, 50, 114504, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
