# Generated by Django 3.0.8 on 2020-08-05 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_auto_20200805_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='currency',
            field=models.CharField(default='SEK', max_length=32),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 7, 18, 59, 420747, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
