# Generated by Django 3.0.8 on 2020-08-05 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_auto_20200805_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 8, 24, 34, 825888, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
