# Generated by Django 3.0.8 on 2020-08-05 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0015_auto_20200805_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='id',
            new_name='essay_id',
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 8, 35, 57, 707469, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
