# Generated by Django 3.0.8 on 2020-08-05 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0019_auto_20200805_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essay_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 8, 59, 27, 152727, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
