# Generated by Django 3.0.8 on 2020-08-05 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0020_auto_20200805_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essay_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 9, 2, 9, 211874, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
