# Generated by Django 3.0.8 on 2020-08-14 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0021_auto_20200805_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='were_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='currency',
            field=models.CharField(default='EUR', max_length=32),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 11, 23, 20, 794214, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
