# Generated by Django 3.0.8 on 2020-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0022_auto_20200814_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_correction_string',
            field=models.TextField(default='No', max_length=500000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date uploaded'),
        ),
    ]
