# Generated by Django 3.0.8 on 2020-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0024_auto_20201025_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='essay_correction_string',
            new_name='essay_correction_json',
        ),
        migrations.AddField(
            model_name='essay',
            name='corrections',
            field=models.TextField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='essay',
            name='errors',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
